### ISSUE TITLE
两个usb总线都能使用？

### ISSUE THREAD

**Issue by akwangl** [htmambo/Lenovo-Air14-ALC-Hackintosh#1]
你是怎么做到的，更新最新的oc么

**Comment by htmambo** [comment]
我现在连那两个usb的kext都不用也正常，可能机器的原因吧。

**Comment by htmambo** [comment]
> 你是怎么做到的，更新最新的oc么


我现在连那两个usb的kext都不用也正常，可能机器的原因吧。

**Comment by skipjackyu** [comment]
红米14 5500u准备折腾一下，Windows Mac双系统，网卡更换ax200
