### ISSUE TITLE
快捷键有问题了

### ISSUE THREAD

**Issue by ssln5014** [htmambo/Lenovo-Air14-ALC-Hackintosh#3]
你好，最新的efi是不是去除了亮度的快捷键？在windows里也不能用了，是我电脑的问题吗，重装了系统和驱动还是不行。

**Comment by htmambo** [comment]
@ssln5014 没有，我的mac和win是正常的。

**Comment by ssln5014** [comment]
> @ssln5014 没有，我的mac和win是正常的。

好吧，我再看看😂

**Comment by ssln5014** [comment]
> @ssln5014 没有，我的mac和win是正常的。

替换了上一个版本的efi，正常了

**Comment by htmambo** [comment]
@ssln5014 就是改了个pnlf的文件名，内容也没改啊。

**Comment by ssln5014** [comment]
> @ssln5014 就是改了个pnlf的文件名，内容也没改啊。

具体我也忘了是哪一版本，我之前备份的没有这三个文件的最后一个版本，
![image](https://github.com/htmambo/Lenovo-Air14-ALC-Hackintosh/assets/81206855/cce2b520-97d7-43e9-85d7-5be9ad1548f5)
下面左边是最新的，右边是之前的
![image](https://github.com/htmambo/Lenovo-Air14-ALC-Hackintosh/assets/81206855/3d3dcf10-f108-4203-93b0-f7eb474f71e2)

**Comment by htmambo** [comment]
@ssln5014 这三个是umaf的，和oc没关系
