### ISSUE TITLE
触控板失灵问题

### ISSUE THREAD

**Issue by lowa9** [htmambo/Lenovo-Air14-ALC-Hackintosh#4]
请问你有遇到进去系统后没多久触控板失灵的情况吗？只能用外接鼠标了

**Comment by htmambo** [comment]
@lowa9 没，一直正常。开机后或者睡眠唤醒后都没遇到过

**Comment by lowa9** [comment]
好吧，我这边是开机后三分钟左右吧，突然就动不了了，然后只能外接鼠标，感觉也不是驱动的问题，因为刚开机是能用的。。。
还是谢谢好兄弟🫡

**Comment by kissesch** [comment]
> 好吧，我这边是开机后三分钟左右吧，突然就动不了了，然后只能外接鼠标，感觉也不是驱动的问题，因为刚开机是能用的。。。 还是谢谢好兄弟🫡

兄弟，我也遇到这个情况了，系统14.7.1。你那现在解决了吗？

**Comment by lowa9** [comment]
没解决，我已经放弃黑苹果了

**Comment by kissesch** [comment]
> 没解决，我已经放弃黑苹果了

噢噢好的吧😂
